"""validation recruteurs, corbeille, champs annonce

Revision ID: 67a28927ae20
Revises: a9d480bbabd5
Create Date: 2026-08-03 13:18:39.736250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a28927ae20'
down_revision = 'a9d480bbabd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('contract_type', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('remote_policy', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('salary_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salary_max', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salary_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_job_offers_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default : les comptes deja presents doivent recevoir une valeur,
        # sinon PostgreSQL refuse l'ajout d'une colonne NOT NULL.
        batch_op.add_column(
            sa.Column('status', sa.String(length=20), nullable=False, server_default='active')
        )
        batch_op.add_column(sa.Column('company', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('phone')
        batch_op.drop_column('company')
        batch_op.drop_column('status')

    with op.batch_alter_table('job_offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_offers_deleted_at'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('salary_currency')
        batch_op.drop_column('salary_max')
        batch_op.drop_column('salary_min')
        batch_op.drop_column('remote_policy')
        batch_op.drop_column('contract_type')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
